version: '3'
services:
  web:
    build: .
    volumes:
      - ./app:/arethusa/app
      - ./dist:/arethusa/dist
      - ./spec:/arethusa/spec
    command: ["grunt", "reloading-server", "--port=$${PORT}"]
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DEV=1
